README.md, build.sh
Plus some adjustment to the `build.sh` help text.
Fixes #3
=> ✏️ Overhaul of the README

Dockerfile
https://redmine.nine.ch/issues/37619
=> Set right version of django rest framework

Dockerfile, docker/configuration.docker.py
.. so I copied it over to this repo.
=> 🐞 The upstream repo remove the docker config

docker/nginx.conf
Set client_max_body_size to 10M so that we can upload images
=> Enable uploading of images

README.md
Fixes #35 . See the issue for the discussion that lead to this change.
=> ✏️ Explain how to do a better backup

docker/configuration.docker.py
=> 🐞 Convert numbers from ENV to int

Dockerfile, build.sh
In this episode:
* Cleanup of the build.sh
* More options to influence the build without touching the build.sh file
* Adds the source of the Netbox code as label to the resulting Docker image
=> ❇️ Adds new options to the build script

README.md
URL in readme was 404, found updated URL.
=> Fix k8s configmap url

.dockerignore, Dockerfile, README.md, docker-compose.test.yml, docker-compose.yml, docker/docker-entrypoint.sh, initializers/custom_fields.yml, initializers/groups.yml, initializers/users.yml, startup_scripts/00_users.py, startup_scripts/10_groups.py, startup_scripts/20_custom_fields.py
Initializers are startup scripts provided for common use-cases like creating Netbox groups, users or custom fields.
Besides this, the `docker-compose.yml` file has been improved and dependent applications have been updated.
Fixes #40.
=> Introduced Initializers

Dockerfile.ldap, README.md, build-branches.sh, build-latest.sh, build.sh, configuration/ldap_config.py, docker/ldap_config.docker.py
Hello,
this is a first proposal for the addition of LDAP enabled images.
Kind regards
Tobias
=> Add django_ldap_auth enabled image

configuration/configuration.py, configuration/ldap_config.py
=> 🐞 Parse config correctly

configuration/configuration.py, netbox.env
=> add allow all hosts by default

configuration/configuration.py
=> 🐞 REDIS_PORT should be int

README.md, initializers/groups.yml, initializers/users.yml, startup_scripts/00_users.py, startup_scripts/10_groups.py
Thank you @bdlamprecht for researching how to add permissions to users and groups in #92.
Fixes #92
=> Add permissions to user/group initializers

DOCKER_HUB.md, README.md, build-all.sh, build-branches.sh, build-latest.sh, build.sh, hooks/build, hooks/common, hooks/push, hooks/test
Instead of building images on Travis this allows to build our images directly on Docker Hub.
=> Build system for hub.docker.com

Dockerfile
This change is in accordance with https://github.com/digitalocean/netbox/issues/2808
=> Loosen version pinning for Django

build.sh
Adds a short version tag in the form of v$MAJOR.$MINOR. This tags
creates the possibillity to follow patch releases automatically with the
scheduled import option in Openshift and Kubernetes. The tag is only added for releases.
=> Add short version tag

initializers/platforms.yml
rpc client was removed from netbox
=> Updating the initializer platform examples

Dockerfile
Just remove a trailing space in Dockerfile
=> Remove trailing space in Dockerfile

.github/ISSUE_TEMPLATE/feature_request.md
This PR suggests to add a new issue category for tracking feature proposals and change requests.
=> A new issue category for feature/change requests

docker-compose.yml
Update Nginx 1.17-alpine docker-compose.yml
=> Update Nginx 1.17-alpine docker-compose.yml

build.sh
=> Remove use of GNU date extensions when labeling images

initializers/rack_groups.yml, initializers/racks.yml, startup_scripts/075_rack_groups.py
Add an additional initialiser script
Fixes #192
I have intentionally not changed the ordering prefix of existing scripts. If this is desired, I can follow up with an additional PR for that.
Signed-off-by: Jeroen Simonetti <jeroen@simonetti.nl>
=> Add rack group initialiser

hooks/test, test.sh
This PR adds a new test that is run on CI an validates that the default initializer yaml files work when they are uncommented.
=> Adds a test that validates the initializer yml files
