- docker/nginx.conf
when using /api/doc/ swagger (openapi) json gets generated wrong host, because django-rest-swagger relies on this header
> use http_host instedad of server_name for X-Forwarded-Host

- .travis.yml
When we built netbox-docker on our internal Jenkins server, we built the following branches and versions:
* `master` branch became the image with the `latest` tag
* `develop` branch became the image with the `snapshot` tag
* _the latest stable version_ was built and tagged with the respective version tag
The travis build enhanced this automatic setup by building also the latest pre-release version, and tagging it accordingly. But building the `develop` branch got forgotten. This is now corrected with this pull request again.
> Builds snapshot image again

- Dockerfile
With the release of [Netbox 2.1.6](https://github.com/digitalocean/netbox/releases/tag/v2.1.6), this workaround is not needed anymore.
> Removes workaround for Django Rest Framework

- README.md
When running in Stable CoreOS, error emerged:
ERROR: The Docker Engine version is less than the minimum required by Compose. Your current project requires a Docker Engine of version 1.13.0 or greater.
Added dependencies
> Project requirements

- Dockerfile
The present build does not include a font-family causing Graphviz to render text as blank squares, including the ttf ubuntu font-family means text is rendered correctly
> Added ttf-ubuntu-font-family

- docker-compose.yml
I found it difficult to remember which volume was associated to which container when it was not specifically named.
This simply names the volume that `postgres` uses for persistent data.
This will also be helpful for backup purposes.
Feel free to squash these two commits as the 2nd simply removed an unnecessary new line.
> Add named volume for postgres data

- README.md
- docker-compose.yml
- docker/docker-entrypoint.sh
This is a general mechanism to launch python scripts for Netbox: All the scripts put inside the `docker/startup_scripts` folder will be executed.
> Load custom fields when creating the container

- Dockerfile
- configuration/gunicorn_config.py
This moves the gunicorn_config.py into /etc/netbox so that it can be
easily mapped through a Openshift config map
> Externalize gunicorn-config

- build.sh
Add the ability to specify a proxy via environment variables for http and https requests done during the docker build process.
> Add proxy support to build.sh

- Dockerfile
Because the tag "python:3.6-alpine" points to Alpine 3.4 which is now
end of life (as of 2018-05-01) the image now pulls the Alpine 3.7 python
image
> Update to Alpine 3.7

- startup_scripts/000_users.py
- startup_scripts/010_groups.py
- startup_scripts/020_custom_fields.py
- startup_scripts/030_regions.py
- startup_scripts/040_sites.py
- startup_scripts/050_manufacturers.py
- startup_scripts/060_device_types.py
- startup_scripts/070_rack_roles.py
- startup_scripts/080_racks.py
- startup_scripts/090_device_roles.py
- startup_scripts/100_platforms.py
- startup_scripts/110_devices.py
Previously, the startup_scripts would fail if an initializer file was
not present. Now they just ignore missing files.
> Ignore missing initializers

- configuration/ldap_config.py
Hello! This PR/commit adds a couple additional env vars that can be used for tweaking the LDAP configuration for servers that deviate from the Active Directory schema. For example, with FreeIPA, the group class used is `ipausergroup` instead of `group`. Likewise, the `sAMAccountName` user attribute does not exist by default.
`AUTH_LDAP_USER_SEARCH_ATTR` - Sets user attribute (default `sAMAccountName`)
`AUTH_LDAP_GROUP_SEARCH_CLASS` - Sets group class (default `group`)
Thanks
> ldap_config: Allow specifying custom user attribute and group classes

- README.md
- docker/docker-entrypoint.sh
To optimize the application boot time the startup scripts can now be
disabled by an ENV variable. The default when the variable is not set,
is to run the startup scripts. This means that the default behaviour is
not changed from earlier releases.
> Make startup scripts optional

- README.md
- configuration/ldap_config.py
Secrets files allow removing authentication passwords out of environment variables, however the bind password for LDAP was left behind. This copies the read_secret function from configuration.py and allows pulling the AUTH_LDAP_BIND_PASSWORD from a secrets file named auth_ldap_bind_password.
> AUTH_LDAP_BIND_PASSWORD secret file support

- configuration/ldap_config.py
Adds support for adding `AUTH_LDAP_GROUP_TYPE` to `netbox.env`, allowing selection of any [django-auth-ldap](https://django-auth-ldap.readthedocs.io/en/latest/groups.html) groups, I.E. for nested groups:
`AUTH_LDAP_GROUP_TYPE=NestedActiveDirectoryGroupType`
Dynamically imports the correct class/subclass from `django_auth_ldap.config` based on the env. Still defaults to `GroupOfNamesType` and leaves original unconfigured functionality unchanged.
> Add AUTH_LDAP_GROUP_TYPE env variable support

- Dockerfile
After [a discussion][1] with @rje6459 on the [networktocode Slack][slack]
in the #netbox-docker channel we've come up with a small improvement
to those that regularly have to build netbox Docker images locally.
It basically fetches the "requirements.txt" from the desired branch before downloading netbox itself.
[1]: https://networktocode.slack.com/archives/CD23LP8BC/p1558537080023200
[slack]: https://networktocode.slack.com
> Caching of requirements.txt

- configuration/configuration.py
Hello,
When `REDIS_PORT` env var is string then netbox crashes during startup. Retyping `REDIS_PORT` to int solves it
> Retype REDIS_PORT to int

- startup_scripts/000_users.py
- startup_scripts/010_groups.py
Permission codenames in django are not unique. This iterates through all permissions of a given name to add individually
closes #146
> adjusts users and groups startup scripts to accomdate non-uniqueness

- Dockerfile
The following errors are detected in ruamel.yaml 0.16:
```
netbox_1         | Traceback (most recent call last):
netbox_1         |   File "./manage.py", line 10, in <module>
netbox_1         |     execute_from_command_line(sys.argv)
netbox_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
netbox_1         |     utility.execute()
netbox_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
netbox_1         | self.fetch_command(subcommand).run_from_argv(self.argv)
netbox_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
netbox_1         |     self.execute(*args, **cmd_options) …
```
> fix AttributeError for ruamel.yaml

- README.md
I've written and will continue to maintain a Helm chart to aid in deploying NetBox on Kubernetes. This adds a link to the README file so that people who may be interested in it can find it.
The chart is currently in use both by myself and my employer and possibly others, and I intend for it to be a production-ready means to deploy NetBox on Kubernetes. I would be very happy to discuss transferring ownership of the chart to the netbox-community group, as well if that would be preferable.
> Add a link to my Helm chart

- .dockerignore
- .gitignore
- DOCKER_HUB.md
- Dockerfile
- README.md
- build-all.sh
- build-latest.sh
- build.sh
- docker-compose.yml
- hooks/push
These changes have the goal to speed up the build because the Docker caching can better be leveraged. They also reduces the Docker Image's size from ~580 MB to ~280MB.
It will be required to use the `build.sh` script to build containers. A 'regular' `docker build` or `docker-compose build` will not work any longer.
* Improved build speed (confirmed, especially with repeating builds)
* Smaller image size (confirmed)
* Instant releases of new `netbox-docker` features (instead of having to wait until the next Netbox release) (unconfirmed)
> Externalize netbox download

- .dockerignore
- .gitignore
- DOCKER_HUB.md
- Dockerfile
- Dockerfile.ldap
- README.md
- build-all.sh
- build-branches.sh
- build-latest.sh
- build.sh
- docker-compose.yml
- hooks/build
- hooks/common
- hooks/push
- hooks/test
This PR contains a big refactoring of the build process and how variants work.
- Dockerfile.ldap was integrated into Dockerfile as a seperate
[build stage][multistage-build].
- The code to fetch the Netbox source was extracted from the Dockerfile. This is now handled by the build script.
- All the build scripts were refactored according to this.
- The `docker-compose.yml` file was adjusted likewise.
- The main build script, `/build.sh`, now always builds all
targets (formerly called variants), i.e. 'main' and 'ldap'.
- The minimal requirements for _Docker_ and _docker-compose_
have increased.
- Test builds for Pull Requests are now possible.
- The images are now less than 100mb most of the time.
- The build speed was improved, especially if a Docker Cache is available.
This change should …
> Refactor to multistage builds

- configuration/configuration.py
- docker-compose.yml
Custom scripts were added to Netbox in version 2.6.3. This adds a new
directory to the image where custom scripts can be placed.
> Add support for custom scripts

- Dockerfile
As mentioned by @sdktr the "--install-option" is redundant. The added
"--no-warn-script-location" is used to silence warnings when installing
into a directory that is not on $PATH.
> Optimize pip install command

- configuration/configuration.py
Defaulting to 300 seconds for the database connection to avoid new connection setup roundtrip on consecutive requests
> Add CONN_MAX_AGE to database connection settings

- Dockerfile
Gunicorn version 20 crashes in this docker image. So for now use a
version <20.
> Fix #179 'libc not found'

- .gitignore
Adding an ignore rule for docker-compose.override.yml should allow people to clone this repo and use an override file to match their environment, without that file causing issues every time they pull a new version of the repo.
> Ignore local override file

- .github/ISSUE_TEMPLATE/bug_report.md
- Dockerfile
- README.md
- build.sh
It also updates the README and the bug_report template to reflect
the changes. Additionally, in the README some relevant shields from
shields.io are added.
The labels follow [label-schema.org][lsorg] and the [OpenContainer image spec, section annotations][ocis], specifications.
And finally, the build script was adjusted to be explicit about the Docker registry that is used, and thereby more easily allowing the use a different registry.
Closes #183 
[lsorg]: http://label-schema.org/rc1/
[ocis]: https://github.com/opencontainers/image-spec/blob/master/annotations.md
> Adds more labels to the Dockerfile

- Dockerfile
This reverts commit feb810ab27bf459a54a3e2055e7c399ed478f1f5, which is PR #180, as Gunicorn introduced [a work-around in v20.0.3][2003] to address the original issue.
Fixes #181.
[2003]: https://github.com/benoitc/gunicorn/releases/tag/20.0.3
> Revert "Fix #179 'libc not found'"

- .dockerignore
Reduces the amount of files that are sent to the Docker builder when building the image.
This also reduces the chances of cache busts because of irrelevant files.
> Reduce the Docker Context

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Related Issue: N/A
Whenever a PR is opened, a default text is added by Github.
The author is asked to provide a short statement on each of to the topics.
Currently each PR contains as much information as the author is willing to share.
Often more context is desired to validate the PR.
Then we have to ask the original author to provide more context about the proposed change, which further delays the change.
In order to have more information readily available when reviewing the change, I suggest to add this PR template.
The drawback could be that people simply ignore the template or that they shy away from filling it in and don't open a PR at all. I believe this risk to be little.
On the plus side, we'll hopefully get PRs of better quality, because the author has to give more context about …
> Pull Request Template Suggestion

- docker/docker-entrypoint.sh
- startup_scripts/__main__.py
The changes in this PR result in a massively reduced execution time of the startup_scripts.
What used to take minutes now takes seconds. This increases the startup time of a Netbox Docker container drastically.
The bottleneck was that `./manage.py shell` was run for every file in the `startup_scripts` folder.
This command takes a while to load, because it has to initialize the whole Django context.
The new solution is that `./manage.py shell` is only loaded once. It is given a piece of python code that loads the `startup_scripts/__main__.py` file. This file contains the remaining code to execute all the startup scripts in the right order.
> Massive speedup in executing startup_scripts

- DOCKER_HUB.md
- README.md
- build-branches.sh
- build.sh
- hooks/common
- hooks/push
This script is a preparation for the changes proposed in #184, i.e. to change to a different branching/development model for this project based on a `develop` and a `release` branch.
> Prepares scripts and documentation for #184

- hooks/common
The builds on Docker Hub were not always successful recently. (E.g. [this build][build])
[build]: https://hub.docker.com/repository/registry-1.docker.io/netboxcommunity/netbox/builds/371ff439-05bd-4062-ae84-cbf7643f7d54
I believe the reason is that some scripts relevant only to the build on Docker Hub were not adjusted to the changes in the build script when I merged #185.
> Fix variables for Dockerhub build
